### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by StefMa** [StefMa/hugo-fresh#65]
I get the following warnings when I build the site:
```
Building sites … 
WARN 2019/07/24 10:37:50 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/07/24 10:37:50 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/07/24 10:37:50 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/07/24 10:37:50 Page's .Dir is deprecated and will be removed in a future release. Use .File.Dir.
WARN 2019/07/24 10:37:50 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
```

(See also #61)
We should fix the warnings

**Comment by nathanbiller** [comment]
I have a branch where I've fixed this, but it's a few commits ahead of other code that I submitted so I'm planning on waiting to submit a PR until my other PRs have been merged.

**Comment by StefMa** [comment]
That cool. Thank you.
Are you aware of [cherry-picks](https://git-scm.com/docs/git-cherry-pick)? 

If its possible with your changes you could create a new branch and cherry-pick your commits into the new branch and create a PR :)

**Comment by Allen616** [comment]
I see this is closed but I am still getting similar errors.

`WARN 2019/11/07 15:00:29 found no layout file for "HTML" for "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/11/07 15:00:29 found no layout file for "HTML" for "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/11/07 15:00:29 found no layout file for "HTML" for "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/11/07 15:00:29 found no layout file for "HTML" for "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/11/07 15:00:29 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/11/07 15:00:29 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/11/07 15:00:29 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/11/07 15:00:29 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/11/07 15:00:29 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.`

**Comment by Allen616** [comment]
I was able to overcome the errors by changing the "disable warnings" format in my config.yaml. 

This is the format that corrected the warnings:

`disableKinds: ["page", "section", "taxonomy", "taxonomyTerm"]
`

Following is the existing format in the [config.yaml](https://github.com/StefMa/hugo-fresh/blob/master/exampleSite/config.yaml), which still created errors :

`disableKinds:
 -taxonomy
 -taxonomyTerm`

I hope this helps others.
